### ISSUE TITLE
TW5 compatibility

### ISSUE THREAD

**Issue by instantkaffee** [dmontaner/TiddlyWikiR#1]
Dear David,
I am very intersted to use your package TiddlyWikiR.
But I am using TW5.
Is it compatible ?

If yes what is the code to start working with the empty.html provided from http://tiddlywiki.com/#GettingStarted ?

**Comment by dmontaner** [comment]
Hi instantkaffee

I have not had much time to dedicate to the library... also I was waiting until TW5 was a bit more settled down. For the moment my library can just work with the classic TiddlyWiki version.

I may catch up if I get a bit of time. 

Thanks for your interest.

**Comment by instantkaffee** [comment]
Dear David,
TW5 is stable now.
It would be super if you could upgrade your package.
Think about the perfect combination of two great tools :-)

Sorry for pushing, eager to hear from you
Regards

**Comment by instantkaffee** [comment]
Hello. David,
I really need a TW5 update.
How to start?

**Comment by instantkaffee** [comment]
Looks like that this repository will not undergo a refresh to TW5. Thats a pitty.
